name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Instalar dependencias necesarias
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    # 3. Configurar, compilar y ejecutar las pruebas
    - name: Configure, Build, and Test
      run: |
        mkdir build
        cd build
        cmake .. -DENABLE_TESTING=ON
        cmake --build .
        ctest --output-on-failure
